### ISSUE TITLE
Where do you implement the combinational equation in your code?

### ISSUE THREAD

**Issue by ardimasp** [rafaelsutiono/home-security-system#1]
I'm wondering where you implement the combinational equation that you derive from your K-map in your C implementation.

**Comment by rafaelsutiono** [comment]
Comment well-received, sir. As a result of your comment, I've been able to discover that my state & transition table includes some fatal mistakes, each of which causes the output, or next state, to display as (1,1), which is impossible to achieve in my FSM based on my diagram. Consequently, this led to my K-Maps deriving the wrong combinatorial boolean equations. Additionally, my K-maps initially did not include "don't cares" for the output (1,1), marking my second set of mistakes. These mistakes went unnoticed as a result of not using the equations in the C implementation but using direct conditions taken directly from the FSM diagram instead. Thank you for opening this issue sir, otherwise, I wouldn't have been able to find these mistakes. 😅😅

I have now made new commits in my repo to address this issue. Here's the full list of commits I made:
- corrected state & transition table (3 commits)
- corrected combinatorial equations
- included combinatorial equations in C
- deleted inaccurate k-map image (2 commits)
- uploaded updated k-map images
